### ISSUE TITLE
[Question] Block IP numbers

### ISSUE THREAD

**Issue by MrBlasyMSK** [JeroGamingYT/NoAdvertisings#1]
Is it possible to ban the numbers?
I mean, if SteveGamer comes and types 12.123.12.123 (the IP of his server) is there any way to block the numbers?

**Comment by 0xliam627** [comment]
Dear @MrBlasyMSK,
> Your problem has been accepted.
NoAdvertising v0.0.6 has improved ip block number, you can download [it here](https://github.com/Eric-pm-pl/NoAdvertisings/releases/tag/v0.0.6)
